Chat/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
urlpatterns =[
    path('',views.home, name='home'),
    path('get',views.chatbot, name='chatbot'),
    path('index',views.index, name='index'),
    path('register',views.register, name='register'),
    url(r'^posts/(?P<slug>[-\w]+)/$', views.single, name='post'),

]

chatbot/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('Chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('carts.urls')),
    path('', include('orders.urls')),
    path('accounts/',include('django.contrib.auth.urls'))

]+ static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
urlpatterns =[

    url(r'checkout', views.checkout, name='checkout'),
    url(r'orders', views.orders, name='user_orders'),



]

orders/models.py
from django.db import models
from carts.models import Cart
from django.contrib.auth import get_user_model
# Create your models here.
User= get_user_model()

STATUS_CHOICES=(
    ("Started","Started"),
    ("Adbandoned","Adbandoned"),
    ("Finished","Finished"),
)



class Order(models.Model):
    #address
    user = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE)
    order_id=models.CharField(max_length=120,default='ABC',unique=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    Sub_total = models.DecimalField(default=0.0, decimal_places=2, max_digits=100000)
    Tax_total = models.DecimalField(default=10.9, decimal_places=2, max_digits=100000)
    Final_total = models.DecimalField(default=10.9, decimal_places=2, max_digits=100000)
    status=models.CharField(max_length=120,choices=STATUS_CHOICES,default="Started")
    timestamp=models.DateTimeField(auto_now_add=True,auto_now=False)
    updated=models.DateTimeField(auto_now_add=False,auto_now=True)

    def __unicode__(self):
        return self.order_id

orders/views.py
from django.shortcuts import render, HttpResponseRedirect
from carts.models import Cart
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Order
from .utils import id_generator

import time


def orders(request):
    context={}
    template="orders/user.html"
    return render(request,template, context)

# Create your views here.
def checkout(request):


    try:
        the_id = request.session['cart_id']
        cart=Cart.objects.get(id=the_id)
    except:
        the_id = None
        return HttpResponseRedirect(reverse("cart"))

    new_order, created= Order.objects.get_or_create(cart=cart)
    if created:
        new_order.order_id= id_generator() #str(time.time())
        new_order.save()
    new_order.user = request.user
    new_order.save()
    if new_order.status == "Finished":
        del request.session['cart_id']
        del request.session['items_total']
    return render(request,"index.html", {})

templates/orders/user.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <div class='col-sm-8 col-sm-offset-2' style="margin-left:200px;">
  <body class="text-center">
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="/index">E-commerce</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">

                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/index">Home</a></li>


                    </ul>
                </div>
            </div>
        </nav>
<div style="margin-top:100px;"> {{user.order_set.all}}</div>

</body>
</html>